swagger: '2.0'
info:
  title: Parsing Bot
  description: API Documentation
  version: 0.0.1
  contact:
    email: cryptocoin62@gmail.com
basePath: /
schemes:
  - http
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /:
    get:
      tags:
        - home
      summary: Handler for home
      operationId: home
      produces:
        - "text/html"
      responses:
        '200':
          description: Successful response
definitions:
  Obj:
    type: object
    properties:
      Timestamp:
        type: string
      Array:
        $ref: '#/definitions/Array'
  Array:
    type: array
    items:
      $ref: '#/definitions/Post'
  Post:
    type: object
    properties:
      Title:
        type: string
      Body:
        type: string
      Hash:
        type: string
      Image:
        type: string
      Link:
        type: string




